name: CI
on:
  push:
    branches:
    - develop
    - master
  
jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Gem Dependencies
      run: bundle install

    - name: Run UnitTests
      run: bundle exec fastlane test